# Работа с параметрами

## Чтение данных

In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)

In [2]:
accepted = pd.read_csv('lending_data/accepted_clean.csv')
accepted.head().transpose()

,0,1,2,3,4
loan_amnt,3600.0,24700.0,10400.0,20000.0,20000.0
installment,123.03,820.28,289.91,637.58,631.26
sub_grade,14,11,26,7,6
emp_length,10,10,3,10,10
home_ownership,MORTGAGE,MORTGAGE,MORTGAGE,MORTGAGE,MORTGAGE
annual_inc,55000.0,65000.0,104433.0,180000.0,85000.0
verification_status,Not Verified,Not Verified,Source Verified,Not Verified,Not Verified
issue_d,2015-12-01,2015-12-01,2015-12-01,2015-12-01,2015-12-01
purpose,debt_consolidation,small_business,major_purchase,debt_consolidation,major_purchase
addr_state,PA,SD,PA,MN,SC
dti,5.91,16.06,25.37,14.67,17.61
delinq_2yrs,0.0,1.0,1.0,0.0,1.0
earliest_cr_line,2003-08-01,1999-12-01,1998-06-01,1990-06-01,1999-02-01
fico_range_low,675.0,715.0,695.0,680.0,705.0
fico_range_high,679.0,719.0,699.0,684.0,709.0
inq_last_6mths,1.0,4.0,3.0,0.0,0.0
open_acc,7.0,22.0,12.0,12.0,8.0
pub_rec,0.0,0.0,0.0,0.0,0.0
total_acc,13.0,38.0,35.0,27.0,15.0
initial_list_status,w,w,w,f,w
last_credit_pull_d,2019-03-01,2019-03-01,2018-03-01,2019-03-01,2019-03-01
collections_12_mths_ex_med,0.0,0.0,0.0,0.0,0.0
acc_now_delinq,0.0,0.0,0.0,0.0,0.0
tot_coll_amt,722.0,0.0,0.0,0.0,0.0
tot_cur_bal,144904.0,204396.0,331730.0,360358.0,141601.0
total_rev_hi_lim,9300.0,111800.0,34000.0,94200.0,14500.0
acc_open_past_24mths,4.0,4.0,10.0,6.0,4.0
avg_cur_bal,20701.0,9733.0,27644.0,30030.0,17700.0
bc_open_to_buy,1506.0,57830.0,4567.0,0.0,13674.0
bc_util,37.2,27.1,77.5,102.9,5.7
chargeoff_within_12_mths,0.0,0.0,0.0,0.0,0.0
delinq_amnt,0.0,0.0,0.0,0.0,0.0
mo_sin_old_il_acct,148.0,113.0,128.0,142.0,149.0
mo_sin_old_rev_tl_op,128.0,192.0,210.0,306.0,55.0
mo_sin_rcnt_rev_tl_op,3.0,2.0,4.0,10.0,32.0
mo_sin_rcnt_tl,3.0,2.0,4.0,10.0,13.0
mort_acc,1.0,4.0,6.0,4.0,3.0
mths_since_recent_bc,4.0,2.0,4.0,12.0,32.0
mths_since_recent_inq,4.0,0.0,1.0,10.0,8.0
num_accts_ever_120_pd,2.0,0.0,0.0,0.0,1.0
num_actv_bc_tl,2.0,5.0,4.0,4.0,2.0
num_actv_rev_tl,4.0,5.0,6.0,6.0,2.0
num_bc_sats,2.0,13.0,5.0,4.0,3.0
num_bc_tl,5.0,17.0,9.0,5.0,3.0
num_il_tl,3.0,6.0,10.0,7.0,9.0
num_op_rev_tl,4.0,20.0,7.0,9.0,3.0
num_rev_accts,9.0,27.0,19.0,16.0,3.0
num_rev_tl_bal_gt_0,4.0,5.0,6.0,6.0,2.0
num_sats,7.0,22.0,12.0,12.0,8.0
num_tl_120dpd_2m,0.0,0.0,0.0,0.0,0.0
num_tl_30dpd,0.0,0.0,0.0,0.0,0.0
num_tl_90g_dpd_24m,0.0,0.0,0.0,0.0,1.0
num_tl_op_past_12m,3.0,2.0,4.0,2.0,0.0
pct_tl_nvr_dlq,76.9,97.4,96.6,96.3,93.3
percent_bc_gt_75,0.0,7.7,60.0,100.0,0.0
pub_rec_bankruptcies,0.0,0.0,0.0,0.0,0.0
tax_liens,0.0,0.0,0.0,0.0,0.0
tot_hi_cred_lim,178050.0,314017.0,439570.0,388852.0,193390.0
total_bal_ex_mort,7746.0,39475.0,95768.0,116762.0,27937.0
total_bc_limit,2400.0,79300.0,20300.0,31500.0,14500.0
total_il_high_credit_limit,13734.0,24667.0,88097.0,46452.0,36144.0
disbursement_method,Cash,Cash,Cash,Cash,Cash
has_been_last_delinq,0,0,0,0,0
has_been_recent_revol_delinq,0,0,0,1,1
has_been_last_major_derog,0,1,1,1,0
has_been_recent_bc_dlq,0,1,0,1,1
has_been_last_record,1,1,1,1,1
duration,36,36,60,36,36
event,False,False,False,False,False

## Конвертация существующих параметров

### Конвертируем даты

In [3]:
dates_cols = ['issue_d', 'earliest_cr_line', 'last_credit_pull_d']

for col in dates_cols:
    accepted[col] = pd.to_datetime(accepted[col])
accepted[dates_cols].dtypes

issue_d               datetime64[ns]
earliest_cr_line      datetime64[ns]
last_credit_pull_d    datetime64[ns]
dtype: object

## Синтетические параметры

In [4]:
accepted.columns

Index(['loan_amnt', 'installment', 'sub_grade', 'emp_length', 'home_ownership',
       'annual_inc', 'verification_status', 'issue_d', 'purpose', 'addr_state',
       'dti', 'delinq_2yrs', 'earliest_cr_line', 'fico_range_low',
       'fico_range_high', 'inq_last_6mths', 'open_acc', 'pub_rec', 'total_acc',
       'initial_list_status', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'acc_now_delinq', 'tot_coll_amt',
       'tot_cur_bal', 'total_rev_hi_lim', 'acc_open_past_24mths',
       'avg_cur_bal', 'bc_open_to_buy', 'bc_util', 'chargeoff_within_12_mths',
       'delinq_amnt', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op',
       'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl', 'mort_acc',
       'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'disbursement_method',
       'has_been_last_delinq', 'has_been_recent_revol_delinq',
       'has_been_last_major_derog', 'has_been_recent_bc_dlq',
       'has_been_last_record', 'duration', 'event'],
      dtype='object')

### Средний FICO

In [5]:
accepted['fico_range_mean'] = (accepted['fico_range_high'] + accepted['fico_range_low']) / 2

### Datetime extract year

In [6]:
dates_cols = ['issue_d', 'earliest_cr_line', 'last_credit_pull_d']

for col in dates_cols:
    accepted[f'{col}_year'] = pd.to_datetime(accepted[col]).dt.year
    accepted[f'{col}_month'] = pd.to_datetime(accepted[col]).dt.month

### Loan Issue Season

In [7]:
accepted['issue_d_season'] = accepted['issue_d'].dt.quarter

## Представление данных

### Переведем колонки с датами к целочисленному виду

In [8]:
dates_cols = ['issue_d', 'earliest_cr_line', 'last_credit_pull_d']

for col in dates_cols:
    accepted[col] = (accepted[col] - pd.to_datetime('1900-01-01')).dt.days
accepted[dates_cols].dtypes

issue_d               int64
earliest_cr_line      int64
last_credit_pull_d    int64
dtype: object

### Переведем оставшиеся категориальные колонки к целочисленному виду

In [9]:
str_cols = list(accepted.select_dtypes(include=['object']).columns)

for cols in str_cols:
    accepted[cols] = accepted[cols].astype('category').cat.codes

In [10]:
accepted.head().transpose()

                                     0         1         2         3         4
loan_amnt                       3600.0   24700.0   10400.0   20000.0   20000.0
installment                     123.03    820.28    289.91    637.58    631.26
sub_grade                           14        11        26         7         6
emp_length                          10        10         3        10        10
home_ownership                       1         1         1         1         1
annual_inc                     55000.0   65000.0  104433.0  180000.0   85000.0
verification_status                  0         0         1         0         0
issue_d                          42337     42337     42337     42337     42337
purpose                              2        11         6         2         6
addr_state                          38        41        38        23        40
dti                               5.91     16.06     25.37     14.67     17.61
delinq_2yrs                        0.0       1.0       1.0       0.0       1.0
earliest_cr_line                 37832     36493     35945     33023     36190
fico_range_low                   675.0     715.0     695.0     680.0     705.0
fico_range_high                  679.0     719.0     699.0     684.0     709.0
inq_last_6mths                     1.0       4.0       3.0       0.0       0.0
open_acc                           7.0      22.0      12.0      12.0       8.0
pub_rec                            0.0       0.0       0.0       0.0       0.0
total_acc                         13.0      38.0      35.0      27.0      15.0
initial_list_status                  1         1         1         0         1
last_credit_pull_d               43523     43523     43158     43523     43523
collections_12_mths_ex_med         0.0       0.0       0.0       0.0       0.0
acc_now_delinq                     0.0       0.0       0.0       0.0       0.0
tot_coll_amt                     722.0       0.0       0.0       0.0       0.0
tot_cur_bal                   144904.0  204396.0  331730.0  360358.0  141601.0
total_rev_hi_lim                9300.0  111800.0   34000.0   94200.0   14500.0
acc_open_past_24mths               4.0       4.0      10.0       6.0       4.0
avg_cur_bal                    20701.0    9733.0   27644.0   30030.0   17700.0
bc_open_to_buy                  1506.0   57830.0    4567.0       0.0   13674.0
bc_util                           37.2      27.1      77.5     102.9       5.7
chargeoff_within_12_mths           0.0       0.0       0.0       0.0       0.0
delinq_amnt                        0.0       0.0       0.0       0.0       0.0
mo_sin_old_il_acct               148.0     113.0     128.0     142.0     149.0
mo_sin_old_rev_tl_op             128.0     192.0     210.0     306.0      55.0
mo_sin_rcnt_rev_tl_op              3.0       2.0       4.0      10.0      32.0
mo_sin_rcnt_tl                     3.0       2.0       4.0      10.0      13.0
mort_acc                           1.0       4.0       6.0       4.0       3.0
mths_since_recent_bc               4.0       2.0       4.0      12.0      32.0
mths_since_recent_inq              4.0       0.0       1.0      10.0       8.0
num_accts_ever_120_pd              2.0       0.0       0.0       0.0       1.0
num_actv_bc_tl                     2.0       5.0       4.0       4.0       2.0
num_actv_rev_tl                    4.0       5.0       6.0       6.0       2.0
num_bc_sats                        2.0      13.0       5.0       4.0       3.0
num_bc_tl                          5.0      17.0       9.0       5.0       3.0
num_il_tl                          3.0       6.0      10.0       7.0       9.0
num_op_rev_tl                      4.0      20.0       7.0       9.0       3.0
num_rev_accts                      9.0      27.0      19.0      16.0       3.0
num_rev_tl_bal_gt_0                4.0       5.0       6.0       6.0       2.0
num_sats                           7.0      22.0      12.0      12.0       8.0
num_tl_120dpd_2m                   0.0       0.0       0.0       0.0       0.0
num_tl_30dpd                       0.0       0.0       0.0       0.0       0.0
num_tl_90g_dpd_24m                 0.0       0.0       0.0       0.0       1.0
num_tl_op_past_12m                 3.0       2.0       4.0       2.0       0.0
pct_tl_nvr_dlq                    76.9      97.4      96.6      96.3      93.3
percent_bc_gt_75                   0.0       7.7      60.0     100.0       0.0
pub_rec_bankruptcies               0.0       0.0       0.0       0.0       0.0
tax_liens                          0.0       0.0       0.0       0.0       0.0
tot_hi_cred_lim               178050.0  314017.0  439570.0  388852.0  193390.0
total_bal_ex_mort               7746.0   39475.0   95768.0  116762.0   27937.0
total_bc_limit                  2400.0   79300.0   20300.0   31500.0   14500.0
total_il_high_credit_limit     13734.0   24667.0   88097.0   46452.0   36144.0
disbursement_method                  0         0         0         0         0
has_been_last_delinq                 0         0         0         0         0
has_been_recent_revol_delinq         0         0         0         1         1
has_been_last_major_derog            0         1         1         1         0
has_been_recent_bc_dlq               0         1         0         1         1
has_been_last_record                 1         1         1         1         1
duration                            36        36        60        36        36
event                            False     False     False     False     False
fico_range_mean                  677.0     717.0     697.0     682.0     707.0
issue_d_year                      2015      2015      2015      2015      2015
issue_d_month                       12        12        12        12        12
earliest_cr_line_year             2003      1999      1998      1990      1999
earliest_cr_line_month               8        12         6         6         2
last_credit_pull_d_year           2019      2019      2018      2019      2019
last_credit_pull_d_month             3         3         3         3         3
issue_d_season                       4         4         4         4         4

## Моделирование целевой переменной

В рамках нашей задачи мы рассматриваем базовое решение и проводим эксперименты.
В рамках базового решения мы будем рассматривать событие, как наступление дефолта в первые 12 месяцев.

In [11]:
accepted['baseline_event'] = ((accepted['event']) & (accepted['duration'] < 12))
accepted[['baseline_event', 'event', 'duration']].head()

   baseline_event  event  duration
0           False  False        36
1           False  False        36
2           False  False        60
3           False  False        36
4           False  False        36

In [12]:
accepted.dropna(inplace=True)
accepted.head().transpose()

                                     0         1         2         3         4
loan_amnt                       3600.0   24700.0   10400.0   20000.0   20000.0
installment                     123.03    820.28    289.91    637.58    631.26
sub_grade                           14        11        26         7         6
emp_length                          10        10         3        10        10
home_ownership                       1         1         1         1         1
annual_inc                     55000.0   65000.0  104433.0  180000.0   85000.0
verification_status                  0         0         1         0         0
issue_d                          42337     42337     42337     42337     42337
purpose                              2        11         6         2         6
addr_state                          38        41        38        23        40
dti                               5.91     16.06     25.37     14.67     17.61
delinq_2yrs                        0.0       1.0       1.0       0.0       1.0
earliest_cr_line                 37832     36493     35945     33023     36190
fico_range_low                   675.0     715.0     695.0     680.0     705.0
fico_range_high                  679.0     719.0     699.0     684.0     709.0
inq_last_6mths                     1.0       4.0       3.0       0.0       0.0
open_acc                           7.0      22.0      12.0      12.0       8.0
pub_rec                            0.0       0.0       0.0       0.0       0.0
total_acc                         13.0      38.0      35.0      27.0      15.0
initial_list_status                  1         1         1         0         1
last_credit_pull_d               43523     43523     43158     43523     43523
collections_12_mths_ex_med         0.0       0.0       0.0       0.0       0.0
acc_now_delinq                     0.0       0.0       0.0       0.0       0.0
tot_coll_amt                     722.0       0.0       0.0       0.0       0.0
tot_cur_bal                   144904.0  204396.0  331730.0  360358.0  141601.0
total_rev_hi_lim                9300.0  111800.0   34000.0   94200.0   14500.0
acc_open_past_24mths               4.0       4.0      10.0       6.0       4.0
avg_cur_bal                    20701.0    9733.0   27644.0   30030.0   17700.0
bc_open_to_buy                  1506.0   57830.0    4567.0       0.0   13674.0
bc_util                           37.2      27.1      77.5     102.9       5.7
chargeoff_within_12_mths           0.0       0.0       0.0       0.0       0.0
delinq_amnt                        0.0       0.0       0.0       0.0       0.0
mo_sin_old_il_acct               148.0     113.0     128.0     142.0     149.0
mo_sin_old_rev_tl_op             128.0     192.0     210.0     306.0      55.0
mo_sin_rcnt_rev_tl_op              3.0       2.0       4.0      10.0      32.0
mo_sin_rcnt_tl                     3.0       2.0       4.0      10.0      13.0
mort_acc                           1.0       4.0       6.0       4.0       3.0
mths_since_recent_bc               4.0       2.0       4.0      12.0      32.0
mths_since_recent_inq              4.0       0.0       1.0      10.0       8.0
num_accts_ever_120_pd              2.0       0.0       0.0       0.0       1.0
num_actv_bc_tl                     2.0       5.0       4.0       4.0       2.0
num_actv_rev_tl                    4.0       5.0       6.0       6.0       2.0
num_bc_sats                        2.0      13.0       5.0       4.0       3.0
num_bc_tl                          5.0      17.0       9.0       5.0       3.0
num_il_tl                          3.0       6.0      10.0       7.0       9.0
num_op_rev_tl                      4.0      20.0       7.0       9.0       3.0
num_rev_accts                      9.0      27.0      19.0      16.0       3.0
num_rev_tl_bal_gt_0                4.0       5.0       6.0       6.0       2.0
num_sats                           7.0      22.0      12.0      12.0       8.0
num_tl_120dpd_2m                   0.0       0.0       0.0       0.0       0.0
num_tl_30dpd                       0.0       0.0       0.0       0.0       0.0
num_tl_90g_dpd_24m                 0.0       0.0       0.0       0.0       1.0
num_tl_op_past_12m                 3.0       2.0       4.0       2.0       0.0
pct_tl_nvr_dlq                    76.9      97.4      96.6      96.3      93.3
percent_bc_gt_75                   0.0       7.7      60.0     100.0       0.0
pub_rec_bankruptcies               0.0       0.0       0.0       0.0       0.0
tax_liens                          0.0       0.0       0.0       0.0       0.0
tot_hi_cred_lim               178050.0  314017.0  439570.0  388852.0  193390.0
total_bal_ex_mort               7746.0   39475.0   95768.0  116762.0   27937.0
total_bc_limit                  2400.0   79300.0   20300.0   31500.0   14500.0
total_il_high_credit_limit     13734.0   24667.0   88097.0   46452.0   36144.0
disbursement_method                  0         0         0         0         0
has_been_last_delinq                 0         0         0         0         0
has_been_recent_revol_delinq         0         0         0         1         1
has_been_last_major_derog            0         1         1         1         0
has_been_recent_bc_dlq               0         1         0         1         1
has_been_last_record                 1         1         1         1         1
duration                            36        36        60        36        36
event                            False     False     False     False     False
fico_range_mean                  677.0     717.0     697.0     682.0     707.0
issue_d_year                      2015      2015      2015      2015      2015
issue_d_month                       12        12        12        12        12
earliest_cr_line_year             2003      1999      1998      1990      1999
earliest_cr_line_month               8        12         6         6         2
last_credit_pull_d_year           2019      2019      2018      2019      2019
last_credit_pull_d_month             3         3         3         3         3
issue_d_season                       4         4         4         4         4
baseline_event                   False     False     False     False     False

Разделим данные для базового решения и для экспериментов.

In [13]:
accepted_se = accepted.drop(columns=['baseline_event'])
accepted_base = accepted.drop(columns=['event'])

## Выгрузка данных

In [14]:
accepted_se.to_csv('lending_data/accepted_se_features.csv', index=False)
accepted_base.to_csv('lending_data/accepted_base_features.csv', index=False)